version: '3'

services:
  api:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - '${FORWARD_PORT:-3000}:${PORT:-3000}'
