version: '3'

services:
  api:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    networks:
      - parking_over_here
    env_file:
      - .env
    command: npm run dev
    ports:
      - '${FORWARD_PORT:-3000}:${PORT:-3000}'
