import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { type ReactNode } from 'react';
import './globals.css';
import Provider from './provider';

const inter = Inter({ subsets: ['latin'] });
inter.className += 'h-full scroll-smooth antialiased';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' className={inter.className}>
      <body className='flex h-full flex-col'>
        <Provider>
          <main className='grow'>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
